### ISSUE TITLE
Ignore @internal check on Drupal\Core\Entity\ContentEntityDeleteForm

### ISSUE THREAD

**Issue by nicrodgers** [mglaman/phpstan-drupal#289]
Apologies, not sure whether this belongs here or in the drupal-check project.  After recently running composer update in one of our drupal projects,  drupal-check is now reporting a number of issues with code that extends ContentEntityDeleteForm.  The message is:

Extend \Drupal\Core\Entity\ContentEntityConfirmFormBase. See https://www.drupal.org/node/2491057

Looking at that drupal.org issue though, it seems that it's pretty stale, and has not yet been adopted in Drupal 9 or 10.  The ContentEntityConfirmFormBase class itself within Drupal core hasn't been modified for 2 years. Therefore it seems a little premature to refactor our code now.  

Is it possible to configure drupal-check/phpstan-drupal to suppress/ignore this particular error?

**Comment by mglaman** [comment]
I thought about this as a fix for #284, instead of linking to the issue. I'd rather folks add it to their ignored errors so we can force the discussion in Drupal core.

You don't need to refactor. Just add it to your ignored errors. Hopefully, the effort to run PHPStan against Drupal core gets this answered.
