### ISSUE TITLE
Don't load excluded files 

### ISSUE THREAD

**Issue by chrfritsch** [mglaman/phpstan-drupal#33]
I have a problem because I have the blazy module in my system. That module declares token_theme, if it does not exist.

Now the autoloader loads first https://cgit.drupalcode.org/blazy/tree/tests/modules/blazy_test/blazy_test.module#n91
and after that the "real" token_theme function. That fails with:

` Fatal error:  Cannot redeclare token_theme`

I wanted to specify an exclude in my config, but that doesn't work

```
parameters:
  excludes_analyse:
    - blazy_test.module
```

What do you think is the best way to fix it?

**Comment by aweingarten** [comment]
I have just encountered the same issue.

**Comment by h3rj4n** [comment]
I've added the following in my phpstan.neon file:

`	autoload_files:
		- web/modules/contrib/token/token.module
`
This way the token is first loaded prior to the blazy module.

**Comment by mglaman** [comment]
There is a workaround. The one problem is that excludes_analyse is not taken into account when bootstrapping Drupal. I'll see if this is possible.

**Comment by mglaman** [comment]
Unfortunately, this is not easy to avoid due to how the file is loaded

```
    protected function loadExtension(Extension $extension): void
    {
        try {
            $extension->load();
        } catch (\Throwable $e) {
            // Something prevented the extension file from loading.
            // This can happen when drupal_get_path or drupal_get_filename are used outside of the scope of a function.
        }
    }
```

This is what adds the `.module` file and it cannot be easily excluded. The bootstrap process also has no context of the service container, which means it cannot respect those configurations.

I don't see any way to fix this beyond adding quick hacks in the bootstrap process as problems are found.

**Comment by TravisCarden** [comment]
FYI: [I filed an issue with the Blazy module](https://www.drupal.org/project/blazy/issues/3037752) for fixing this. The maintainer expressed willingness to commit a patch fixing the problem, if provided, but does not intend to address it otherwise. Since I don't have bandwidth to refactor the module, I provided a patch there that simply removes the offending code for anyone who wants to use it.
