### ISSUE TITLE
Run phpstan under webroot

### ISSUE THREAD

**Issue by JTubex** [mglaman/phpstan-drupal#46]
Currently, phpstan only works when running the command in the directory where Drupal is located.

Is it possible to run the command under the webroot? e.g.:
`www/vendor/bin/phpstan analyse www/modules/custom`

**Comment by mglaman** [comment]
PHPStan needs to be able to load the autoloader for Drupal. So you must run PHPStan from the root of your Drupal project so it can detect the autoloader.

Now, I wonder if we could actually improve this:

```
        $finder = new DrupalFinder();
        $finder->locateRoot(dirname($GLOBALS['autoloaderInWorkingDirectory'], 2));
        $this->drupalRoot = $finder->getDrupalRoot();
```

Instead of basing it off of `autoloaderInWorkingDirectory`, I wonder if we could determine the Drupal root based off of the provided path.  We would then need to include the autoloader if it was not. 

This is some of the magic in PHPStan

```
$autoloaderInWorkingDirectory = getcwd() . '/vendor/autoload.php';
if (is_file($autoloaderInWorkingDirectory)) {
	require_once $autoloaderInWorkingDirectory;
}

$composerAutoloadFile = __DIR__ . '/../vendor/autoload.php';
if (!is_file($composerAutoloadFile)) {
	$composerAutoloadFile = __DIR__ . '/../../../autoload.php';
}

require_once $composerAutoloadFile;
```

I'll try and experiment. But it might be possible to fix this by taking in the target path's folder and passing that to DrupalFinder.

**Comment by mglaman** [comment]
Drupal Check https://github.com/mglaman/drupal-check does this. But that doesn't allow for customized PHPStan config, it started as mostly a helper for deprecation discovery

**Comment by JTubex** [comment]
Reason i’m asking: We use GrumPHP (https://github.com/phpro/grumphp) to run some checks when committing. The commands are run from the directory where the .git directory is located. For us, this is under the webroot.

**Comment by JTubex** [comment]
I created PR #50.

Instead of using  $GLOBALS['autoloaderInWorkingDirectory'], I used $GLOBALS['composerAutoloadFile'] which did the trick for me.

**Comment by mglaman** [comment]
I'll begin reviewing the PR. I hate GitHub. It fractures discussions and code reviews.

**Comment by mglaman** [comment]
Per my comments on the PR, I think the only fix is allowing an explicit parameter definition which specifies where Drupal's root is located and we detect the autoloader based off of that path.

**Comment by JTubex** [comment]
When using the master-branch, this works using the following phpstan.neon file:
````
parameters:
	level: 7
drupal:
    drupal_root: %currentWorkingDirectory%/htdocs
includes:
	- htdocs/vendor/mglaman/phpstan-drupal/extension.neon
````

**Comment by mglaman** [comment]
:) @JTubex cool, you beat me to that. I was going to commit and document this and mention you. Thanks for confirming
