### ISSUE TITLE
FieldItem::getEntity() can actually return null, not always EntityInterface

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#501]
Let's stub this and fix it.

**Comment by rivimey** [comment]
The issue is in FieldItemInterface::getEntity() which can return NULL but is documented as:

```
  /**
   * Gets the entity that field belongs to.
   *
   * @return \Drupal\Core\Entity\FieldableEntityInterface
   *   The entity object.
   */
  public function getEntity();
```

Obvs the need is to mark it as:

```
   * @return \Drupal\Core\Entity\FieldableEntityInterface|null
```

**Comment by rivimey** [comment]
This patch might be the right thing?

```
diff -u mglaman/phpstan-drupal/stubs/Drupal/Core/Field/FieldItemInterface.stub mglaman/phpstan-drupal/stubs/Drupal/Core/Field/FieldItemInterface.stub 
--- mglaman/phpstan-drupal/stubs/Drupal/Core/Field/FieldItemInterface.stub        2022-07-18 18:17:55.000000000 +0100
+++ mglaman/phpstan-drupal/stubs/Drupal/Core/Field/FieldItemInterface.stub    2023-01-25 21:12:49.682578081 +0000
@@ -2,7 +2,14 @@
 
 namespace Drupal\Core\Field;
 
+use Drupal\Core\Entity\FieldableEntityInterface;
 use Drupal\Core\TypedData\ComplexDataInterface;
 
 interface FieldItemInterface extends ComplexDataInterface {
+
+    /**
+     * @return \Drupal\Core\Entity\FieldableEntityInterface|null
+     */
+    public function getEntity();
+
 }
```

**Comment by mglaman** [comment]
Traversing through, FieldItem calls parent typed data object which calls the FieldItemList. The FieldItemList calls its parent, the EntityAdapter typed data object. 

The `\Drupal\Core\Entity\Plugin\DataType\EntityAdapter` data type has a bunch of checks for null but also warnings if the value is null.

I'm curious what path leads to there be a null entity on a field item or field item list? That means the typed data objects were somehow instantiated outside an entity context.

**Comment by rivimey** [comment]
The situation was that (having got a valid field object), calling getEntity() on it was considered by phpstan to always return a valid EntityInterface (actually a FieldableEntityInterface) object.

The code, however, was trying to account for the valid possibility of there being no Entity to return and so of getEntity() returning Null.

Phpstan was then complaining that there was no point in checking for Null on the returned value because the return was 'known' to always be non-Null.

My patch above just added `|null` to try to indicate to phpstan that the return could in fact be Null or an Entity.

**Comment by mglaman** [comment]
`getEntity` is always the "owner" of the field. For instance of entity reference, it is _not_ the referenced entity. 

```
$node->get('field_my_ref')->getEntity() // returns $node
$node->get('field_my_ref')->get(0)->getEntity() // returns $node
$node->get('field_my_ref')->get(0)->entity // returns $entity_ref

```
