### ISSUE TITLE
Support RevisionableStorageInterface and methods ::loadRevision() and ::deleteRevision() deprecation

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#549]
# Feature request

https://github.com/mglaman/drupal-change-record-triage/issues/518

PHPStan gets confused because methods are shared across interfaces. So we need stubs to add `@not-deprecated` onto specific stubs.

**Comment by driskell** [comment]
Hi - I seem to still have this issue with latest Phpstan. I think because `ContentEntityStorageInterface` extends `EntityStorageInterface` as well as `TranslatableRevisionableStorageInterface` - the latter extending `RevisionableStorageInterface`

With PHPstan 1.1.36 we're having to use `RevisionableStorageInterface` as the type hint now and we can't use `ContentEntityStorageInterface`

**Comment by mglaman** [comment]
Thanks for reporting!
